verifiy common.json file before using it

diff --git a/reg/reg_all b/reg/reg_all
--- a/reg/reg_all
+++ b/reg/reg_all
@@ -541,9 +541,9 @@ EOF
 reg_microservice_common_attributes()
 {
     # do not need this if it is second or more time running the script
-    if [[ $REREG -eq 1 ]]; then
-        return $RC_SUCCESS
-    fi
+    #if [[ $REREG -eq 1 ]]; then
+    #    return $RC_SUCCESS
+    #fi
 
     if [[ $VERBOSE -eq 1 ]]; then
         echo "Register common service attributes."
@@ -553,6 +553,14 @@ reg_microservice_common_attributes()
     fn="$SCRIPT_DIR/common.json"
     if [ -f $fn ]; then
         all_attributes=$(envsubst < $fn)
+
+        # make sure the common.js has valid json format
+        ret=$(echo $all_attributes | jq '.' 2>&1)
+        if [ $? -ne 0 ]; then
+            echo -e "The file $fn contains errors:\n $ret\nPlease fix it and re-run this command."
+            return $RC_FAILED_REG_SERVICE_ATTRIBS_ANAX
+        fi
+
         len=$(echo "$all_attributes" | jq 'length')
 
         # check the common attribute one by one, skil the ones that have no data.
